import { serve } from "bun";
import { chat, toServerSentEventsResponse, toolDefinition } from "@tanstack/ai";
import { openRouterText } from "@tanstack/ai-openrouter";
import { z } from "zod";
import OpenAI from "openai";
import { createAgent, tool } from "langchain";
import * as z from "zod";

import index from "./index.html";
import {
  fetchPriceDef,
  getPriceDef,
  getCryptoPriceDef,
} from "@/tool";

const getXAUTPriceInputSchema: JSONSchema = {
  type: "object",
  properties: {
    time: {
      type: "date",
      description: "the time of price being asked, default latest (right now)",
    },
  },
};

const getXAUTPriceOutputSchema: JSONSchema = {
  type: "object",
  properties: {
    price: {
      type: "number",
      description: "the price of XAUT in USD"
    },
  },
  required: ["price"],
};

export const getXAUTPriceDef = toolDefinition({
  name: 'get_XAUTPrice',
  description: 'Get the latest price of XAUT token or known as Gold',
  inputSchema: getXAUTPriceInputSchema,
  outputSchema: getXAUTPriceOutputSchema,
});

// Define schemas using JSON Schema
const inputSchema: JSONSchema = {
  type: "object",
  properties: {
    location: {
      type: "string",
      description: "The city and state, e.g. San Francisco, CA",
    },
    unit: {
      type: "string",
      enum: ["celsius", "fahrenheit"],
    },
  },
  required: ["location"],
};

const outputSchema: JSONSchema = {
  type: "object",
  properties: {
    temperature: { type: "number" },
    conditions: { type: "string" },
    location: { type: "string" },
  },
  required: ["temperature", "conditions", "location"],
};

// Create the tool definition
const getWeatherDef = toolDefinition({
  name: "get_weather",
  description: "Get the current weather for a location",
  inputSchema,
  outputSchema,
});

const getWeather = tool(
  (input) => `It's always sunny in ${input.city}`,
  {
    name: "get_weather",
    description: "Get the weather for a given city",
    schema: z.object({
      city: z.string().describe("The city to get the weather for"),
    }),
  },
);

const langchainAIHandler = async req => {
  const responseFormat = z.object({
    punny_response: z.string(),
    professional_response: z.string(),
    casual_response: z.string(),
  });

  const agent = createAgent({
    model: "gpt-5-nano-2025-08-07",
    tools: [getWeather],
    responseFormat,
  });

  const result = await agent.invoke({
    messages: [
      {
        role: "user",
	content: "What's the weather in Tokyo?",
      },
    ],
  });

  console.log({ result });

  console.log(result.structuredResponse);

  return Response.json({
    message: "ok",
  });
};

const langchainAIStreamHandler = async req => {
  const responseFormat = z.object({
    friendly_response: z.string(),
  });

  const agent = createAgent({
    model: "gpt-5-nano-2025-08-07",
    tools: [getWeather],
    responseFormat,
  });

  const stream = await agent.stream({
    messages: [
      {
        role: "user",
	content: "What's the weather in Tokyo?",
      },
    ]
  },
  { streamMode: "messages" },
  );

  for await (const chunk of stream) {
    const latestMessage = chunk.messages.at(-1);
    if (latestMessage?.content) {
      console.log(`Agent: ${latestMessage.content}`);
    } else if (latestMessage?.tool_calls) {
      const toolCallNames = latestMessage.tool_calls.map((tc) => tc.name);
      console.log(`Calling tools: ${toolCallNames.join(", ")}`);
    }
  }

  return toServerSentEventsResponse(stream);
};

const client = new OpenAI();

const tools = [
  {
    type: "function",
    name: "get_horoscope",
    description: "Get today's horoscope for an astrological sign.",
    parameters: {
      type: "object",
      properties: {
        sign: {
	  type: "string",
	  description: "An astrological sign like Taurus or Aquarius",
	},
      },
      required: ["sign"],
    },
  },
];

const getHoroscope = ({ sign }) => {
  console.log("getHoroscope, ", sign);
  return sign + " Next Tuesday you will befriend a baby otter.";
}

const openAIHandler = async req => {
  const response = await client.responses.create({
    model: "gpt-5-nano",
    input: [
      { role: "user", content: "What is my horoscope? I am an Aquarius." },
    ],
    tools,
  });

  console.log(response.output_text);

  let input = [];
  response.output.forEach((item) => {
    if (item.type == "function_call") {
      if (item.name == "get_horoscope") {
        const horoscope = getHoroscope(JSON.parse(item.arguments));
	input.push({
	  type: "function_call_output",
	  call_id: item.call_id,
	  output: JSON.stringify({
	    horoscope,
	  }),
	});
      }
    }
  });

  console.log("Final input:");
  console.log(JSON.stringify(input, null, 2));

  const newResponse = await client.responses.create({
    model: "gpt-5-nano",
    instructions: "Respond only with a horoscope generated by a tool.",
    input,
    tools,
  });

  return Response.json({
    message: newResponse.output_text,
  });
};

const aiHandler = async req => {
  const { messages, conversationId } = await req.json();

  const getXAUTPrice = getXAUTPriceDef.server(async () => {
    console.log("getting XAUT Price");
    return { price: 4900 };
  });

  // Create server implementation (args is typed as `any` with JSON Schema)
  const getWeather = getWeatherDef.server(async (args) => {
    console.log("calling getWeather");
    const { location, unit } = args;
    const response = await fetch(
      `https://api.weather.com/v1/current?location=${location}&unit=${unit || "fahrenheit"}`
    );
    return await response.json();
  });

  const fetchPrice = fetchPriceDef.server(({ symbol }) => {
    return { symbol, price: 6969 };
  });

  const getPrice = getPriceDef.server(({ symbol }) => {
    return { symbol, price: 69696 };
  });

  const getCryptoPrice = getCryptoPriceDef.server(({ symbol }) => {
    console.log("calling get crypto price");
    return { symbol, price: 6969 };
  });

  const stream = chat({
    // adapter: openRouterText("google/gemma-3n-e2b-it:free"),//openRouterText("arcee-ai/trinity-large-preview:free"),
    adapter: openRouterText("arcee-ai/trinity-large-preview:free"),
    messages,
    conversationId,
    systemPrompts: [
      "You are Yunos, from Yunos AI",
      "You are an agentic on-chain fund manager to hedge your money and act as an agentic wallet interface",
      "You MUST use the get_crypto_price tool whenever the user asks for a token price. Do not answer price questions directly.",
      "You reply by chat, by default your reply is brief unless user ask for a detailed response but never in markdown format",
      "Your wording tone is friendly but professional",
      "You don't speak financial and crypto lingo but you understand them if user ask it",
    ],
    tools: [
      // getXAUTPrice,
      getWeather,
      // fetchPrice,
      getCryptoPrice,
      // getPrice,
    ],
  });

  return toServerSentEventsResponse(stream);
};

const server = serve({
  routes: {
    // Serve index.html for all unmatched routes.
    "/*": index,

    "/api/ai/chat": {
      POST: aiHandler
    },

    "/api/openai/chat": {
      POST: openAIHandler,
    },

    "/api/langchainai/chat": {
      POST: langchainAIHandler,
    },

    "/api/langchainai/stream": {
      POST: langchainAIStreamHandler,
    },

    "/api/hello": {
      async GET(req) {
        return Response.json({
          message: "Hello, world!",
          method: "GET",
        });
      },
      async PUT(req) {
        return Response.json({
          message: "Hello, world!",
          method: "PUT",
        });
      },
    },

    "/api/hello/:name": async req => {
      const name = req.params.name;
      return Response.json({
        message: `Hello, ${name}!`,
      });
    },
  },

  development: process.env.NODE_ENV !== "production" && {
    // Enable browser hot reloading in development
    hmr: true,

    // Echo console logs from the browser to the server
    console: true,
  },
});

console.log(`🚀 Server running at ${server.url}`);
